version: "2"
services:
  authelia:
    image: jekyll/jekyll:3.8
    container_name: jekyll
    volumes:
      - "/home/jstines/docker/tacohacks:/srv/jekyll"
      - "/home/jstines/docker/tacohks/vendor/bundle:/usr/local/bundle"

    networks:
      proxy:
        ipv4_address: 172.26.0.3
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    command:
      "jekyll serve"
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
    #healthcheck:
    #  disable: true

networks:
  proxy:
    external: true

